import { IListTokens } from "../../../../interfaces";

export const TOKENS_JAIN_AND_OUTSITE: IListTokens[] = [
  {
    index: 0,
    positionGame: "BOTTOM_LEFT",
    tokens: [
      {
        color: "RED",
        coordinate: { x: 39, y: 273 },
        typeTile: "JAIL",
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "RED",
        coordinate: { x: 182, y: 312 },
        typeTile: "EXIT",
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "RED",
        coordinate: { x: 91, y: 273 },
        typeTile: "JAIL",
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "RED",
        coordinate: { x: 91, y: 325 },
        typeTile: "JAIL",
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 1,
    positionGame: "TOP_LEFT",
    tokens: [
      {
        color: "GREEN",
        coordinate: { x: 39, y: 39 },
        typeTile: "JAIL",
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: "GREEN",
        coordinate: { x: 39, y: 91 },
        typeTile: "JAIL",
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: "GREEN",
        coordinate: { x: 26, y: 182 },
        typeTile: "EXIT",
        positionTile: 0,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
      {
        color: "GREEN",
        coordinate: { x: 91, y: 91 },
        typeTile: "JAIL",
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: false,
      },
    ],
  },
  {
    index: 2,
    positionGame: "TOP_RIGHT",
    tokens: [
      {
        color: "YELLOW",
        coordinate: { x: 273, y: 39 },
        typeTile: "JAIL",
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "YELLOW",
        coordinate: { x: 273, y: 91 },
        typeTile: "JAIL",
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "YELLOW",
        coordinate: { x: 325, y: 39 },
        typeTile: "JAIL",
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "YELLOW",
        coordinate: { x: 196, y: 153 },
        typeTile: "END",
        positionTile: 0,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
  {
    index: 3,
    positionGame: "BOTTOM_RIGHT",
    tokens: [
      {
        color: "BLUE",
        coordinate: { x: 273, y: 273 },
        typeTile: "JAIL",
        positionTile: 0,
        index: 0,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "BLUE",
        coordinate: { x: 273, y: 325 },
        typeTile: "JAIL",
        positionTile: 1,
        index: 1,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "BLUE",
        coordinate: { x: 325, y: 273 },
        typeTile: "JAIL",
        positionTile: 2,
        index: 2,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
      {
        color: "BLUE",
        coordinate: { x: 325, y: 325 },
        typeTile: "JAIL",
        positionTile: 3,
        index: 3,
        diceAvailable: [],
        totalTokens: 1,
        position: 1,
        enableTooltip: false,
        isMoving: false,
        animated: false,
        canSelectToken: true,
      },
    ],
  },
];
